# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Point2One
                                 A QGIS plugin
 This plugin joins the vector layer of points into one line / polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-20
        copyright            : (C) 2020 by Frommeltová Eva, Hnilicová Lucie, Hudeček Martin 
        email                : lucie.hnilicova@seznam.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Point2One class from file Point2One.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Point2One import Point2One
    return Point2One(iface)
